# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/mpags-day-4-eobrien2502/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/mpags-day-4-eobrien2502

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/mpags-day-4-eobrien2502/CMakeFiles /workspaces/mpags-day-4-eobrien2502//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/mpags-day-4-eobrien2502/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mpags-cipher

# Build rule for target.
mpags-cipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpags-cipher
.PHONY : mpags-cipher

# fast build rule for target.
mpags-cipher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/build
.PHONY : mpags-cipher/fast

#=============================================================================
# Target rules for targets named MPAGSCipher

# Build rule for target.
MPAGSCipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MPAGSCipher
.PHONY : MPAGSCipher

# fast build rule for target.
MPAGSCipher/fast:
	$(MAKE) $(MAKESILENT) -f MPAGSCipher/CMakeFiles/MPAGSCipher.dir/build.make MPAGSCipher/CMakeFiles/MPAGSCipher.dir/build
.PHONY : MPAGSCipher/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f Documentation/CMakeFiles/doc.dir/build.make Documentation/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named testHello

# Build rule for target.
testHello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testHello
.PHONY : testHello

# fast build rule for target.
testHello/fast:
	$(MAKE) $(MAKESILENT) -f Testing/CMakeFiles/testHello.dir/build.make Testing/CMakeFiles/testHello.dir/build
.PHONY : testHello/fast

#=============================================================================
# Target rules for targets named testCatch

# Build rule for target.
testCatch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testCatch
.PHONY : testCatch

# fast build rule for target.
testCatch/fast:
	$(MAKE) $(MAKESILENT) -f Testing/CMakeFiles/testCatch.dir/build.make Testing/CMakeFiles/testCatch.dir/build
.PHONY : testCatch/fast

#=============================================================================
# Target rules for targets named testTransformChar

# Build rule for target.
testTransformChar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTransformChar
.PHONY : testTransformChar

# fast build rule for target.
testTransformChar/fast:
	$(MAKE) $(MAKESILENT) -f Testing/CMakeFiles/testTransformChar.dir/build.make Testing/CMakeFiles/testTransformChar.dir/build
.PHONY : testTransformChar/fast

#=============================================================================
# Target rules for targets named testProcessCommandLine

# Build rule for target.
testProcessCommandLine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testProcessCommandLine
.PHONY : testProcessCommandLine

# fast build rule for target.
testProcessCommandLine/fast:
	$(MAKE) $(MAKESILENT) -f Testing/CMakeFiles/testProcessCommandLine.dir/build.make Testing/CMakeFiles/testProcessCommandLine.dir/build
.PHONY : testProcessCommandLine/fast

#=============================================================================
# Target rules for targets named testCaesarCipher

# Build rule for target.
testCaesarCipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testCaesarCipher
.PHONY : testCaesarCipher

# fast build rule for target.
testCaesarCipher/fast:
	$(MAKE) $(MAKESILENT) -f Testing/CMakeFiles/testCaesarCipher.dir/build.make Testing/CMakeFiles/testCaesarCipher.dir/build
.PHONY : testCaesarCipher/fast

mpags-cipher.o: mpags-cipher.cpp.o
.PHONY : mpags-cipher.o

# target to build an object file
mpags-cipher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.o
.PHONY : mpags-cipher.cpp.o

mpags-cipher.i: mpags-cipher.cpp.i
.PHONY : mpags-cipher.i

# target to preprocess a source file
mpags-cipher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.i
.PHONY : mpags-cipher.cpp.i

mpags-cipher.s: mpags-cipher.cpp.s
.PHONY : mpags-cipher.s

# target to generate assembly for a file
mpags-cipher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.s
.PHONY : mpags-cipher.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doc"
	@echo "... MPAGSCipher"
	@echo "... mpags-cipher"
	@echo "... testCaesarCipher"
	@echo "... testCatch"
	@echo "... testHello"
	@echo "... testProcessCommandLine"
	@echo "... testTransformChar"
	@echo "... mpags-cipher.o"
	@echo "... mpags-cipher.i"
	@echo "... mpags-cipher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

